@startuml
'https://plantuml.com/sequence-diagram

package vues{

    class SujetObserve(){
        ArrayList<Observateur> listObservateurs
        public SujetObserve()
        notifierObservateurs()
        ajouterObservateurs(Observateur o)

    }

    interface Observateur {
        void reagir();
    }

    SujetObserve "1"--"*" Observateur

    class VueActiviteIG() implements Observateur{
        MondeIG mondeIG
        public VueActiviteIG(MondeIG mondeIG)
        void reagir()
    }

    class VueArcIG() implements Observateur{
        MondeIG mondeIG
        public VueArcIG(MondeIG mondeIG)
        void reagir()
    }

    class VueClientIG() implements Observateur{
        MondeIG mondeIG
        public VueClientIG(MondeIG mondeIG)
        void reagir()
    }

    class VueEtapeIG() implements Observateur{
        MondeIG mondeIG
        public VueEtapeIG(MondeIG mondeIG)
        void reagir()
    }

    class VueGuichetIG() implements Observateur{
        MondeIG mondeIG
        public VueGuichetIG(MondeIG mondeIG)
        void reagir()
    }

    class VueMenuIG() implements Observateur{
        MondeIG mondeIG
        public VueMenuIG(MondeIG mondeIG)
        void reagir()
    }

    class VueMondeIG() implements Observateur{
        MondeIG mondeIG
        public VueMondeIG(MondeIG mondeIG)
        void reagir()
    }

    class VueOutils() implements Observateur{
        MondeIG mondeIG
        public VueOutils(MondeIG mondeIG)
        void reagir()
    }

    class VuePointDeControleIG() implements Observateur{
        MondeIG mondeIG
        public VuePointDeControleIG(MondeIG mondeIG)
        void reagir()
    }
}

@enduml